#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: ssbt
# REQUIRE: LOGIN
#
# Add the following lines to /etc/rc.conf to enable ssbt:
#
# ssbt_enable (boot):  Set it to "YES" to enable automatic pull on startup.
# ssbt_dir (str):      Backup directory for ssbt (mandatory!)
# ssbt_user (str):     User to run ssbt as. (default: backup)
# ssbt_flags (str):    Command to run at startup. (default: pull)

. /etc/rc.subr

name="ssbt"
rcvar="ssbt_enable"

command="/usr/local/sbin/ssbt"

load_rc_config $name

: ${ssbt_dir="/nonexistent"}
: ${ssbt_user="backup"}
: ${ssbt_flags="pull"}

run_rc_command "$1"
